name = input("Привет! Как тебя зовут? ")
print(f"Привет, {name}! Давай немного познакомимся.")
kol_years = input("Сколько тебе лет? ")
print(f"Хороший возраст - " + kol_years + " лет=)")
city = input("Из какого ты города? ")
print(f"Echo: {city} - красивый город!")
