import time


name = input(" Добрый день! Введите свое имя  ")
time.sleep(1)
print(f" Привет, {name}. Меня зовут Олеся.")
time.sleep(2)
old = input(f" {name}, сколько тебе лет?  ")
print(f" И мне столько же {old}")
time.sleep(2)
city = input(" Из какого ты города?  ")
time.sleep(1)
print(f" Ты не поверишь, и я из {city}а")
time.sleep(2)
study = input(f" {name},ты пойдешь сегодня на занятие по Python?  ")
time.sleep(2)
print(" Отлично! А я не смогу прийти, так как с малышкой не с кем сидеть.")
time.sleep(4)
study1 = input(" Ты огорчился что я не буду присутствовать онлайн?  ")
time.sleep(3)
print(f" Твой ответ:{study1} - меня подбадривает. Я обязательно буду смотреть запись!  ")
time.sleep(3)
study2 = input(" В какой папке будет находится запись?  ")
time.sleep(2)
print(f" Я посмотрю в {study2} и к следующему уроку выполню задание.")
time.sleep(1)
input("нажмите enter" )
print(f" До встречи, {name}")
time.sleep(1)
input("Если хотите попращаться, то пишите: ")